var myOdds = [1,2,3,4,5,6,7,8,9];
var myMagic = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100];
var myData = [
"a gold braclet",
"a gold ring",
"a silver bracelet",
"a bag of oranges",
"a ball of twine",
"a basket of fresh bread",
"a bullseye lantern",
"a bundle of torches",
"a ball of string",
"a chain mail shirt",
"a coil of hemp rope",
"a collapsable spyglass",
"a doll",
"a few fishhooks",
"a fishing net",
"a full waterskin",
"a glass mirror",
"a gold plated brooch",
"a gourd full of honey",
"a grappling hook",
"a half empty wine bottle",
"a hammer",
"a harp",
"a heafty sledge hammer",
"a hefty crowbar",
"a hefty studded belt",
"a hooded lantern",
"a lantern",
"a leather thong",
"a length of metal wire",
"a light wooden shield",
"a lock with a key in it",
"a long pole",
"a medium sized chisel",
"a metal bell",
"a metal gauntlet",
"a metal hoop",
"a mining pick",
"a pack of sewing needles wrapped by thread",
"a pair of gold ear rings",
"a pair of greives",
"a pair of tiny vambraces",
"a pocket sized hourglass",
"a pocket sized magnifying glass",
"a pocket sized sundial",
"a pot of paint",
"a pouch containing flint, tinder, and steel",
"a pouch of caltrops",
"a pouch of jerkey",
"a pouch of prunes",
"a pretty colored corset",
"a quiver of arrows",
"a quiver of bolts",
"a rolled parchment scroll",
"a rolled scroll",
"a rolled up canvas",
"a section of metal chain",
"a set of leather braces",
"a set of pitons",
"a shovel",
"a shrunken head",
"a silver bracelet",
"a silver locket",
"a small barrel",
"a small black gem",
"a small cage containing some chickens",
"a small green gem",
"a small locked chest",
"a small lyre",
"a small knife",
"a small pouch which appears to be full of sand",
"a small purple gem",
"a small red gem",
"a small saw",
"a small yellow gem",
"a tin bucket",
"a long spear with a quality metal tip",
"a water skin",
"a well used buckler",
"a well used clay tankard",
"a wheel of cheese",
"a whetstone",
"a wide leather belt",
"a wooden bracelet",
"a wooden whistle",
"a wool blanket",
"a wovern basket",
"a pint flask of oil",
"an ounce of ink",
"an attractive silver chain",
"an axe",
"an empty backpack",
"an empty clay jug with a stopper",
"an empty flask",
"an empty sack",
"an empty vial with stopper",
"an evelope of paper sheets",
"an flask filled with some liquid",
"an inkpen",
"an well tooled breast plate armor",
"an iron cooking pot",
"some candles",
"some glass marbles",
"some pieces of chalk",
"some sealing wax",
"some soap",
"some string",
"trail rations",
"what appears to be a signet ring",
"what appears to be a wooden holy symbol",
];
