<?php
// http://simplehtmldom.sourceforge.net/
require('simple_html_dom.php');
$acountry= array();
array_push($acountry,array("ABW","Aruba"));
array_push($acountry,array("AFG","Afghanistan"));
array_push($acountry,array("AGO","Angola"));
array_push($acountry,array("AIA","Anguilla"));
array_push($acountry,array("ALA","Aland Islands"));
array_push($acountry,array("ALB","Albania"));
array_push($acountry,array("AND","Andorra"));
array_push($acountry,array("ARE","United Arab Emirates"));
array_push($acountry,array("ARG","Argentina"));
array_push($acountry,array("ARM","Armenia"));
array_push($acountry,array("ASM","American Samoa"));
array_push($acountry,array("ATA","Antarctica"));
array_push($acountry,array("ATF","French Southern Territories"));
array_push($acountry,array("ATG","Antigua and Barbuda"));
array_push($acountry,array("AUS","Australia"));
array_push($acountry,array("AUT","Austria"));
array_push($acountry,array("AZE","Azerbaijan"));
array_push($acountry,array("BDI","Burundi"));
array_push($acountry,array("BEL","Belgium"));
array_push($acountry,array("BEN","Benin"));
array_push($acountry,array("BES","Caribbean Netherlands"));
array_push($acountry,array("BFA","Burkina Faso"));
array_push($acountry,array("BGD","Bangladesh"));
array_push($acountry,array("BGR","Bulgaria"));
array_push($acountry,array("BHR","Bahrain"));
array_push($acountry,array("BHS","Bahamas"));
array_push($acountry,array("BIH","Bosnia and Herzegovina"));
array_push($acountry,array("BLM","Saint Barthslemy"));
array_push($acountry,array("BLR","Belarus"));
array_push($acountry,array("BLZ","Belize"));
array_push($acountry,array("BMU","Bermuda"));
array_push($acountry,array("BOL","Bolivia"));
array_push($acountry,array("BRA","Brazil"));
array_push($acountry,array("BRB","Barbados"));
array_push($acountry,array("BRN","Brunei Darussalam"));
array_push($acountry,array("BTN","Bhutan"));
array_push($acountry,array("BVT","Bouvet Island"));
array_push($acountry,array("BWA","Botswana"));
array_push($acountry,array("CAF","Central African Republic"));
array_push($acountry,array("CAN","Canada"));
array_push($acountry,array("CCK","Cocos Islands"));
array_push($acountry,array("CHE","Switzerland"));
array_push($acountry,array("CHL","Chile"));
array_push($acountry,array("CHN","China"));
array_push($acountry,array("CIV","Cote dIvoire"));
array_push($acountry,array("CMR","Cameroon"));
array_push($acountry,array("COD","Congo, The Democratic Republic of the"));
array_push($acountry,array("COG","Congo"));
array_push($acountry,array("COK","Cook Islands"));
array_push($acountry,array("COL","Colombia"));
array_push($acountry,array("COM","Comoros"));
array_push($acountry,array("CPV","Cape Verde"));
array_push($acountry,array("CRI","Costa Rica"));
array_push($acountry,array("CUB","Cuba"));
array_push($acountry,array("CUW","Curacao"));
array_push($acountry,array("CXR","Christmas Island"));
array_push($acountry,array("CYM","Cayman Islands"));
array_push($acountry,array("CYP","Cyprus"));
array_push($acountry,array("CZE","Czech Republic"));
array_push($acountry,array("DEU","Germany"));
array_push($acountry,array("DJI","Djibouti"));
array_push($acountry,array("DMA","Dominica"));
array_push($acountry,array("DNK","Denmark"));
array_push($acountry,array("DOM","Dominican Republic"));
array_push($acountry,array("DZA","Algeria"));
array_push($acountry,array("ECU","Ecuador"));
array_push($acountry,array("EGY","Egypt"));
array_push($acountry,array("ERI","Eritrea"));
array_push($acountry,array("ESH","Western Sahara"));
array_push($acountry,array("ESP","Spain"));
array_push($acountry,array("EST","Estonia"));
array_push($acountry,array("ETH","Ethiopia"));
array_push($acountry,array("FIN","Finland"));
array_push($acountry,array("FJI","Fiji"));
array_push($acountry,array("FLK","Falkland Islands"));
array_push($acountry,array("FRA","France"));
array_push($acountry,array("FRO","Faroe Islands"));
array_push($acountry,array("FSM","Micronesia, Federated States of"));
array_push($acountry,array("GAB","Gabon"));
array_push($acountry,array("GBR","United Kingdom"));
array_push($acountry,array("GEO","Georgia"));
array_push($acountry,array("GGY","Guernsey"));
array_push($acountry,array("GHA","Ghana"));
array_push($acountry,array("GIB","Gibraltar"));
array_push($acountry,array("GIN","Guinea"));
array_push($acountry,array("GLP","Guadeloupe"));
array_push($acountry,array("GMB","Gambia"));
array_push($acountry,array("GNB","Guinea-Bissau"));
array_push($acountry,array("GNQ","Equatorial Guinea"));
array_push($acountry,array("GRC","Greece"));
array_push($acountry,array("GRD","Grenada"));
array_push($acountry,array("GRL","Greenland"));
array_push($acountry,array("GTM","Guatemala"));
array_push($acountry,array("GUF","French Guiana"));
array_push($acountry,array("GUM","Guam"));
array_push($acountry,array("GUY","Guyana"));
array_push($acountry,array("HKG","Hong Kong"));
array_push($acountry,array("HMD","Heard Island and McDonald Islands"));
array_push($acountry,array("HND","Honduras"));
array_push($acountry,array("HRV","Croatia"));
array_push($acountry,array("HTI","Haiti"));
array_push($acountry,array("HUN","Hungary"));
array_push($acountry,array("IDN","Indonesia"));
array_push($acountry,array("IMN","Isle of Man"));
array_push($acountry,array("IND","India"));
array_push($acountry,array("IOT","British Indian Ocean Territory"));
array_push($acountry,array("IRL","Ireland"));
array_push($acountry,array("IRN","Iran, Islamic Republic of"));
array_push($acountry,array("IRQ","Iraq"));
array_push($acountry,array("ISL","Iceland"));
array_push($acountry,array("ISR","Israel"));
array_push($acountry,array("ITA","Italy"));
array_push($acountry,array("JAM","Jamaica"));
array_push($acountry,array("JEY","Jersey"));
array_push($acountry,array("JOR","Jordan"));
array_push($acountry,array("JPN","Japan"));
array_push($acountry,array("KAZ","Kazakhstan"));
array_push($acountry,array("KEN","Kenya"));
array_push($acountry,array("KGZ","Kyrgyzstan"));
array_push($acountry,array("KHM","Cambodia"));
array_push($acountry,array("KIR","Kiribati"));
array_push($acountry,array("KNA","Saint Kitts and Nevis"));
array_push($acountry,array("KOR","Korea, Republic of"));
array_push($acountry,array("KWT","Kuwait"));
array_push($acountry,array("LAO","Lao, Peoples Democratic Republic"));
array_push($acountry,array("LBN","Lebanon"));
array_push($acountry,array("LBR","Liberia"));
array_push($acountry,array("LBY","Libyan Arab Jamahiriya"));
array_push($acountry,array("LCA","Saint Lucia"));
array_push($acountry,array("LIE","Liechtenstein"));
array_push($acountry,array("LKA","Sri Lanka"));
array_push($acountry,array("LSO","Lesotho"));
array_push($acountry,array("LTU","Lithuania"));
array_push($acountry,array("LUX","Luxembourg"));
array_push($acountry,array("LVA","Latvia"));
array_push($acountry,array("MAC","Macau"));
array_push($acountry,array("MAF","Saint Martin"));
array_push($acountry,array("MAR","Morocco"));
array_push($acountry,array("MCO","Monaco"));
array_push($acountry,array("MDA","Moldova"));
array_push($acountry,array("MDG","Madagascar"));
array_push($acountry,array("MDV","Maldives"));
array_push($acountry,array("MEX","Mexico"));
array_push($acountry,array("MHL","Marshall Islands"));
array_push($acountry,array("MKD","Macedonia, The Former Yugoslav Republic of"));
array_push($acountry,array("MLI","Mali"));
array_push($acountry,array("MLT","Malta"));
array_push($acountry,array("MMR","Myanmar"));
array_push($acountry,array("MNE","Montenegro"));
array_push($acountry,array("MNG","Mongolia"));
array_push($acountry,array("MNP","Northern Mariana Islands"));
array_push($acountry,array("MOZ","Mozambique"));
array_push($acountry,array("MRT","Mauritania"));
array_push($acountry,array("MSR","Montserrat"));
array_push($acountry,array("MTQ","Martinique"));
array_push($acountry,array("MUS","Mauritius"));
array_push($acountry,array("MWI","Malawi"));
array_push($acountry,array("MYS","Malaysia"));
array_push($acountry,array("MYT","Mayotte"));
array_push($acountry,array("NAM","Namibia"));
array_push($acountry,array("NCL","New Caledonia"));
array_push($acountry,array("NER","Niger"));
array_push($acountry,array("NFK","Norfolk Island"));
array_push($acountry,array("NGA","Nigeria"));
array_push($acountry,array("NIC","Nicaragua"));
array_push($acountry,array("NIU","Niue"));
array_push($acountry,array("NLD","Netherlands"));
array_push($acountry,array("NOR","Norway"));
array_push($acountry,array("NPL","Nepal"));
array_push($acountry,array("NRU","Nauru"));
array_push($acountry,array("NZL","New Zealand"));
array_push($acountry,array("OMN","Oman"));
array_push($acountry,array("PAK","Pakistan"));
array_push($acountry,array("PAN","Panama"));
array_push($acountry,array("PCN","Pitcairn"));
array_push($acountry,array("PER","Peru"));
array_push($acountry,array("PHL","Philippines"));
array_push($acountry,array("PLW","Palau"));
array_push($acountry,array("PNG","Papua New Guinea"));
array_push($acountry,array("POL","Poland"));
array_push($acountry,array("PRI","Puerto Rico"));
array_push($acountry,array("PRK","Korea, Democratic Peoples Republic of"));
array_push($acountry,array("PRT","Portugal"));
array_push($acountry,array("PRY","Paraguay"));
array_push($acountry,array("PSE","Palestinian Territory"));
array_push($acountry,array("PYF","French Polynesia"));
array_push($acountry,array("QAT","Qatar"));
array_push($acountry,array("REU","Reunion"));
array_push($acountry,array("ROU","Romania"));
array_push($acountry,array("RUS","Russian Federation"));
array_push($acountry,array("RWA","Rwanda"));
array_push($acountry,array("SAU","Saudi Arabia"));
array_push($acountry,array("SDN","Sudan"));
array_push($acountry,array("SEN","Senegal"));
array_push($acountry,array("SGP","Singapore"));
array_push($acountry,array("SGS","South Georgia and the South Sandwich Islands"));
array_push($acountry,array("SHN","Saint Helena"));
array_push($acountry,array("SJM","Svalbard and Jan Mayen"));
array_push($acountry,array("SLB","Solomon Islands"));
array_push($acountry,array("SLE","Sierra Leone"));
array_push($acountry,array("SLV","El Salvador"));
array_push($acountry,array("SMR","San Marino"));
array_push($acountry,array("SOM","Somalia"));
array_push($acountry,array("SPM","Saint Pierre and Miquelon"));
array_push($acountry,array("SRB","Serbia"));
array_push($acountry,array("SSD","South Sudan"));
array_push($acountry,array("STP","Sao Tome and Principe "));
array_push($acountry,array("SUR","Suriname"));
array_push($acountry,array("SVK","Slovakia"));
array_push($acountry,array("SVN","Slovenia"));
array_push($acountry,array("SWE","Sweden"));
array_push($acountry,array("SWZ","Swaziland"));
array_push($acountry,array("SXM","Sint Maarten"));
array_push($acountry,array("SYC","Seychelles"));
array_push($acountry,array("SYR","Syrian Arab Republic"));
array_push($acountry,array("TCA","Turks and Caicos Islands"));
array_push($acountry,array("TCD","Chad"));
array_push($acountry,array("TGO","Togo"));
array_push($acountry,array("THA","Thailand"));
array_push($acountry,array("TJK","Tajikistan"));
array_push($acountry,array("TKL","Tokelau"));
array_push($acountry,array("TKM","Turkmenistan"));
array_push($acountry,array("TLS","Timor-Leste"));
array_push($acountry,array("TON","Tonga"));
array_push($acountry,array("TTO","Trinidad and Tobago"));
array_push($acountry,array("TUN","Tunisia"));
array_push($acountry,array("TUR","Turkey"));
array_push($acountry,array("TUV","Tuvalu"));
array_push($acountry,array("TWN","Taiwan"));
array_push($acountry,array("TZA","Tanzania, United Rep."));
array_push($acountry,array("UGA","Uganda"));
array_push($acountry,array("UKR","Ukraine"));
array_push($acountry,array("UMI","United States Minor Outlying Islands"));
array_push($acountry,array("URY","Uruguay"));
array_push($acountry,array("USA","United States"));
array_push($acountry,array("UZB","Uzbekistan"));
array_push($acountry,array("VAT","Holy See"));
array_push($acountry,array("VCT","Saint Vincent and the Grenadines"));
array_push($acountry,array("VEN","Venezuela"));
array_push($acountry,array("VGB","Virgin Islands, British"));
array_push($acountry,array("VIR","Virgin Islands, U.S."));
array_push($acountry,array("VNM","Viet Nam"));
array_push($acountry,array("VUT","Vanuatu"));
array_push($acountry,array("WLF","Wallis and Futuna"));
array_push($acountry,array("WSM","Samoa"));
array_push($acountry,array("YEM","Yemen"));
array_push($acountry,array("ZAF","South Africa"));
array_push($acountry,array("ZMB","Zambia"));
array_push($acountry,array("ZWE","Zimbabwe"));

$acust= array();
array_push($acust,"ANGOLA");
array_push($acust,"ANGUILLA");
array_push($acust,"ANTIGUA AND BARBUDA");
array_push($acust,"ARUBA");
array_push($acust,"AUSTRALIA");
array_push($acust,"AZERBAIJAN");
array_push($acust,"BAHAMAS");
array_push($acust,"BARBADOS");
array_push($acust,"BELIZE");
array_push($acust,"BERMUDA");
array_push($acust,"BOLIVIA");
array_push($acust,"BRAZIL");
array_push($acust,"BULGARIA");
array_push($acust,"CAMEROON");
array_push($acust,"CANADA");
array_push($acust,"CAYMAN ISLANDS");
array_push($acust,"CHILE");
array_push($acust,"CHINA");
array_push($acust,"COLOMBIA");
array_push($acust,"COSTA RICA");
array_push($acust,"COTE DIVOIRE");
array_push($acust,"CYPRUS");
array_push($acust,"DOMINICA");
array_push($acust,"DOMINICAN REPUBLIC");
array_push($acust,"ECUADOR");
array_push($acust,"ESTONIA");
array_push($acust,"FINLAND");
array_push($acust,"FRANCE");
array_push($acust,"GABON");
array_push($acust,"GAMBIA");
array_push($acust,"GEORGIA");
array_push($acust,"GERMANY");
array_push($acust,"GHANA");
array_push($acust,"GREECE");
array_push($acust,"GRENADA");
array_push($acust,"GUATEMALA");
array_push($acust,"GUINEA");
array_push($acust,"HAITI");
array_push($acust,"HONG KONG");
array_push($acust,"ICELAND");
array_push($acust,"INDIA");
array_push($acust,"IRELAND");
array_push($acust,"ISRAEL");
array_push($acust,"ITALY");
array_push($acust,"JAMAICA");
array_push($acust,"JAPAN");
array_push($acust,"JORDAN");
array_push($acust,"KAZAKHSTAN");
array_push($acust,"KENYA");
array_push($acust,"KUWAIT");
array_push($acust,"LATVIA");
array_push($acust,"LEBANON");
array_push($acust,"LITHUANIA");
array_push($acust,"MALTA");
array_push($acust,"MONGOLIA");
array_push($acust,"NEPAL");
array_push($acust,"NETHERLANDS");
//array_push($acust,"NETHERLANDS ANTILLES");
array_push($acust,"NEW ZEALAND");
array_push($acust,"NIGER");
array_push($acust,"NIGERIA");
array_push($acust,"NORWAY");
array_push($acust,"PAKISTAN");
array_push($acust,"PANAMA");
array_push($acust,"PARAGUAY");
array_push($acust,"PERU");
array_push($acust,"PHILIPPINES");
array_push($acust,"POLAND");
array_push($acust,"PORTUGAL");
array_push($acust,"PUERTO RICO");
array_push($acust,"MOLDOVA");
array_push($acust,"RUSSIAN FEDERATION");
array_push($acust,"RWANDA");
array_push($acust,"SAINT KITTS AND NEVIS");
array_push($acust,"SAINT LUCIA");
array_push($acust,"SAINT VINCENT AND THE GRENADINES");
array_push($acust,"SAMOA");
array_push($acust,"SIERRA LEONE");
array_push($acust,"SINGAPORE");
array_push($acust,"SOLOMON ISLANDS");
array_push($acust,"SOUTH AFRICA");
array_push($acust,"SPAIN");
array_push($acust,"SURINAME");
array_push($acust,"SWEDEN");
array_push($acust,"TAIWAN");
array_push($acust,"TRINIDAD AND TOBAGO");
array_push($acust,"TURKEY");
array_push($acust,"TURKS AND CAICOS ISLANDS");
array_push($acust,"UGANDA");
array_push($acust,"UKRAINE");
array_push($acust,"UNITED ARAB EMIRATES");
array_push($acust,"UNITED KINGDOM");
array_push($acust,"UNITED STATES");
array_push($acust,"UNITED STATES MINOR OUTLYING ISLANDS");
array_push($acust,"URUGUAY");
array_push($acust,"VENEZUELA");
array_push($acust,"VIRGIN ISLANDS, U.S.");
array_push($acust,"YEMEN");
array_push($acust,"ZAMBIA");

//foreach ($acust as $cust) {
//    //echo("$cust \n");
//    $found = false;
//    foreach ($acountry as $county) {
//        if (strtoupper($county[1]) == $cust) {
//            //echo("found: $cust \n");
//            $found = true;
//            continue;
//
//        }else{
//        }
//    }
//    if (!$found) {
//        echo("missing: $cust \n");
//    }
////    if(!array_search(strtoupper($county[1]), $acust)){
////        echo "Not found: " . $county[1] . PHP_EOL;
////    }else{
////    }
//}
//

$file = basename(__FILE__,'.php').'.data';
$fp = fopen($file, 'w');
fwrite($fp, date("Y-m-d H:i:s") . PHP_EOL);
foreach ($acountry as $county) {
    if(!array_search(strtoupper($county[1]), $acust)){
        //echo "Not found: " . $county[1] . PHP_EOL;
    }else{
        $foo = lookup($county[0]);
        fwrite($fp, $foo . PHP_EOL . PHP_EOL);
        echo $foo . PHP_EOL;
        echo '--------------------------------------------------------------------------' . PHP_EOL;
    }
}
fwrite($fp, date("Y-m-d H:i:s") . PHP_EOL);

function lookup($code) {
    $out = "";
    $html = file_get_html("https://www.informatica.com/products/data-quality/data-as-a-service/address-verification/address-formats.html?code=$code")->plaintext;
    $start = strpos($html,'Format:');
    $end = strpos($html,'PO Box indicator:');
    if ($end > $start) {
        $data = substr($html, $start+7, $end-($start+7));
        $out = html_entity_decode(trim($data));
    }
    return $out;
}
?>